apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: express-test
spec:
  containers:
    - name: node
      image: node:14
      command:
        - cat
      tty: true
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
    - name: kubectl
      image: lachlanevenson/k8s-kubectl:latest
      command:
        - cat
      tty: true
